Chapter-2: 2-16.cpp 2-17a.cpp 2-17b.cpp 2-17c.cpp 2-18.cpp 2-19.cpp 2-20.cpp\
	       2-21.cpp 2-22.cpp 2-23.cpp 2-24.cpp 2-25.cpp 2-26a.cpp 2-26b.cpp\
	       2-27.cpp 2-28.cpp 2-29.cpp 2-30.cpp
	mkdir ../bin
	g++ -o ../bin/2-16 2-16.cpp
	g++ -o ../bin/2-17a 2-17a.cpp
	g++ -o ../bin/2-17b 2-17b.cpp
	g++ -o ../bin/2-17c 2-17c.cpp
	g++ -o ../bin/2-18 2-18.cpp
	g++ -o ../bin/2-19 2-19.cpp
	g++ -o ../bin/2-20 2-20.cpp
	g++ -o ../bin/2-21 2-21.cpp
	g++ -o ../bin/2-22 2-22.cpp
	g++ -o ../bin/2-23 2-23.cpp
	g++ -o ../bin/2-24 2-24.cpp
	g++ -o ../bin/2-25 2-25.cpp
	g++ -o ../bin/2-26a 2-26a.cpp
	g++ -o ../bin/2-26b 2-26b.cpp
	g++ -o ../bin/2-27 2-27.cpp
	g++ -o ../bin/2-28 2-28.cpp
	g++ -o ../bin/2-29 2-29.cpp
	g++ -o ../bin/2-30 2-30.cpp

.PHONY: clean
clean:
	rm ../bin/2-16 ../bin/2-17a ../bin/2-17b ../bin/2-17c ../bin/2-18\
       ../bin/2-19 ../bin/2-20 ../bin/2-21 ../bin/2-22 ../bin/2-23 ../bin/2-24\
       ../bin/2-25 ../bin/2-26a ../bin/2-26b ../bin/2-27 ../bin/2-28\
       ../bin/2-29 ../bin/2-30
